#!/usr/bin/python
import datetime


def get_calendar_week():
    now = datetime.datetime.now()
    return datetime.date(now.year, now.month, now.day).isocalendar()[1]

week = get_calendar_week()
print("current calendar week: " + str(week))
