#!/usr/bin/python

import sys
from lxml import html
import requests

arguments = sys.argv

word = ""
maxResults = 3

if len(arguments) == 1:
    exit("usage: syn WORD [MAX_RESULTS]")
elif len(arguments) == 2:
    word = arguments[1]
elif len(arguments) == 3:
    word = arguments[1]
    maxResults = int(arguments[2])

page = requests.get("http://synonyme.woxikon.de/synonyme/"+word+".php")
tree = html.fromstring(page.text)

synonymeDivs = tree.xpath("//*[contains(@class, 'synonymsFrame')]")

if len(synonymeDivs) == 0:
    exit("word not found")

results = 0

for div in synonymeDivs[0].getchildren():
    if results >= maxResults:
        exit()
    synonymsGroup = div.getchildren()[1]
    synonymsContent = div.getchildren()[2]

    synonym = synonymsGroup.getchildren()[0].getchildren()[1].text
    print(synonym)
    results += 1
    for synonymsMeaning in synonymsContent.getchildren()[0].getchildren():
        if synonymsMeaning.text is None:
            print("\t"+synonymsMeaning.getchildren()[0].text)
        else:
            print("\t"+synonymsMeaning.text)

