#!/usr/bin/python

import sys
from collections import defaultdict
from lxml import html
import requests


def extract_arguments():
    arguments = sys.argv
    word = ""
    max_results = 3
    if len(arguments) == 1:
        exit("usage: syn WORD [MAX_RESULTS]")
    elif len(arguments) == 2:
        word = arguments[1]
    elif len(arguments) == 3:
        word = arguments[1]
        max_results = int(arguments[2])
    return word, max_results


def get_synonym_divs(word):
    page = requests.get("http://synonyme.woxikon.de/synonyme/" + word + ".php")
    tree = html.fromstring(page.text)
    return tree.xpath("//*[contains(@class, 'synonymsFrame')]")


def get_synonyms(synonym_divs, max_results):
    synonyms = defaultdict(list)
    results = 0
    for div in synonym_divs[0].getchildren():
        if results >= max_results:
            break
        synonyms_group = div.getchildren()[1]
        synonyms_content = div.getchildren()[2]
        synonym = synonyms_group.getchildren()[0].getchildren()[1].text
        results += 1
        for synonyms_meaning in synonyms_content.getchildren()[0].getchildren():
            if synonyms_meaning.text is None:
                synonyms[synonym].append(synonyms_meaning.getchildren()[0].text)
            else:
                synonyms[synonym].append(synonyms_meaning.text)
    return synonyms


def print_synonyms(synonyms):
    for synonym in synonyms.keys():
        print(synonym)
        for meaning in synonyms.get(synonym):
            print("\t" + meaning)


input_word, max_results = extract_arguments()
synonym_divs = get_synonym_divs(input_word)

if len(synonym_divs) == 0:
    exit("word not found")

synonyms = get_synonyms(synonym_divs, max_results)
print_synonyms(synonyms)
